
package vista.cliente;

import vista.AbstractViewImpl;
import controlador.ClienteController;
import java.util.ArrayList;
import java.util.List;
import modelo.entidades.Cliente;

public class ClienteViewImpl extends AbstractViewImpl<ClienteController> implements ClienteView {

    //Atributos propios de Swing
    private ClienteTableAndComboModel tableModel;
    private TableModel2 tableModel2;
    private ClienteViewImplInternal panelCliente;

    /** Creates new form ClienteViewImpl */
    public ClienteViewImpl() {
        //tableModel = new ClienteTableAndComboModel();
        tableModel = ClienteTableAndComboModel.create();
        tableModel2 = TableModel2.create();
        initComponents();
        tableModel.setClienteView(this);
        tableModel2.setClienteView(this);

        this.panelCliente = new ClienteViewImplInternal(this);
        this.jPanelCliente.add(this.panelCliente);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jPanelCliente = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTableClientes.setModel(tableModel);
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        jPanelCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelCliente.setLayout(new javax.swing.BoxLayout(jPanelCliente, javax.swing.BoxLayout.LINE_AXIS));

        jTable1.setModel(tableModel2);
        jScrollPane2.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                    .addComponent(jPanelCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        ClienteTableAndComboModel ctm = (ClienteTableAndComboModel) this.jTableClientes.getModel();     
        Cliente contacto = ctm.getRow(this.jTableClientes.getSelectedRow());
        panelCliente.setContacto(contacto);
    }//GEN-LAST:event_jTableClientesMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelCliente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableClientes;
    // End of variables declaration//GEN-END:variables

    public void refresh() {
        tableModel.setClientes(getController().listaClienteEntidadGesture());//cambia el modelo de JTable(TableModel) por medio de una clase que hemos creado (ContactosTableModel)
        tableModel2.setClientes(getController().listaDatos());
       
    }

    protected void fireNuevoClienteGesture(String DNI, String nombre, String direccion) {
        List<String> datos = new ArrayList<String>();
        datos.add(DNI);
        datos.add(nombre);
        datos.add(direccion);
        getController().nuevaEntidadGesture(datos);
    }

    protected void fireActualizaClienteGesture(String DNI, String nombre, String direccion) {
        List<String> datos = new ArrayList<String>();
        datos.add(DNI);
        datos.add(nombre);
        datos.add(direccion);
        getController().actualizaEntidadGesture(datos);        
    }

    protected void fireBorraClienteGesture(String nombre) {
        getController().borraEntidadGesture(nombre);
    }
}
